tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      sudo apt-get update && sudo apt-get install -y cockpit wget && cd /tmp && wget https://gitlab.com/YottaDB/DB/YDB/raw/master/sr_unix/ydbinstall.sh && sudo chmod +x ydbinstall.sh && sudo ./ydbinstall.sh --installdir /usr/local/yottadb/ --utf8 default --verbose

